[build-system]
requires = ["setuptools>=82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "purism"
version = "2.1.0"
description = "Automatic data filtering library specialized in Korean data purification"
authors = [
  {name="Lumia101"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "transformers",
    "lingua-language-detector",
    "datasketch[redis]",
    "ftfy",
    "joblib",
    "tqdm"
]

[project.urls]
"Homepage" = "https://github.com/Lumia101/purism/tree/main"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"purism.resources" = ["*.txt"]